### ISSUE TITLE
COMPLETE THE CSS AND THE QUIZ QUESTIONS 

### ISSUE THREAD

**Issue by JaGPR** [laughingclouds/quiz-game#33]
THE CSS OF LEFT OVER HTML PAGES IS LEFT SO PLEASE COMPLETE IT  AND THE QUIZ  QUESTIONS ARE ALSO LEFT 
@JaGPR @laughingclouds @PrateekSarna-24 @Shreya220 @MadhaviGupta18

**Comment by laughingclouds** [comment]
I'm working on the styling on [this branch](https://github.com/laughingclouds/quiz-game/tree/css-styling).
